import {Link,useRouterState} from '@tanstack/react-router';
import {useState,type ReactNode} from 'react';
import {useStore} from './context';
import {Button,Icon} from './ui';
import {money,filterProducts} from '@/data/mock';
export function Brand(){const{settings}=useStore();return <Link to="/" className="brand"><span className="brand-mark"><Icon name="leaf" size={40}/></span><span><span className="brand-name">{settings.name}</span><span className="brand-tagline block">ANIMAL HEALTH & LIVESTOCK CARE</span></span></Link>}
const nav=[['/','Home'],['/shop','Shop'],['/categories','Categories'],['/animal-care','Animal Care'],['/about','About'],['/contact','Contact']] as const;
export function WebsiteShell({children}:{children:ReactNode}){const{cart,wishlist,settings}=useStore();const[mobile,setMobile]=useState(false),[search,setSearch]=useState(false);const path=useRouterState({select:s=>s.location.pathname});return <><div className="topbar"><div className="container"><span><Icon name="leaf" size={13}/> Healthier animals. Happier farms.</span><span><Icon name="pin" size={13}/> Sangli-Madhavnagar, Maharashtra</span><a href={`tel:${settings.phone.replace(/\s/g,'')}`}><Icon name="phone" size={13}/>{settings.phone}</a></div></div><header className="navbar"><div className="container nav-inner"><Brand/><nav className="navlinks" aria-label="Main navigation">{nav.map(([to,label])=><Link key={to} to={to} className={path===to?'active':''}>{label}</Link>)}</nav><div className="nav-actions"><Button variant="ghost" className="icon-btn" title="Search products" aria-label="Search products" onClick={()=>setSearch(true)}><Icon name="search"/></Button><Link to="/account" search={{tab:'Wishlist'}} className="icon-btn" title="Wishlist" aria-label="Wishlist"><Icon name="heart"/>{wishlist.length>0&&<span className="count">{wishlist.length}</span>}</Link><Link to="/cart" className="icon-btn" title="Shopping cart" aria-label="Shopping cart"><Icon name="cart"/><span className="count">{Object.values(cart).reduce((a,b)=>a+b,0)}</span></Link><Link to="/account" search={{tab:'Profile'}} className="icon-btn account-icon" title="My account" aria-label="My account"><Icon name="user"/></Link><Link to="/shop" className="btn btn-primary">Shop Now <Icon name="arrow" size={14}/></Link><Button variant="ghost" className="icon-btn mobile-toggle" aria-label={mobile?'Close menu':'Open menu'} onClick={()=>setMobile(!mobile)}><Icon name={mobile?'close':'menu'}/></Button></div></div>{mobile&&<nav className="mobile-menu" aria-label="Mobile navigation">{nav.map(([to,label])=><Link key={to} to={to} onClick={()=>setMobile(false)}>{label}</Link>)}<Link to="/account" search={{tab:'Profile'}} onClick={()=>setMobile(false)}>My Account</Link></nav>}</header>{children}<Footer/>{search&&<SearchModal close={()=>setSearch(false)}/>}</>}
function Footer(){const{settings}=useStore();return <footer className="footer"><div className="container"><div className="footer-grid"><div><Brand/><p>Quality animal health, nutrition and livestock care products. Rooted in care. Dedicated to your farm.</p></div><div><h3>Quick Links</h3><div className="footer-links">{nav.filter(n=>n[0]!=='/animal-care').map(([to,label])=><Link key={to} to={to}>{label}</Link>)}</div></div><div><h3>Customer</h3><div className="footer-links"><Link to="/account" search={{tab:'Profile'}}>My Account</Link><Link to="/account" search={{tab:'My Orders'}}>My Orders</Link><Link to="/account" search={{tab:'Wishlist'}}>Wishlist</Link><Link to="/cart">Shopping Cart</Link><Link to="/checkout">Checkout</Link></div></div><div><h3>Visit or Get in Touch</h3><div className="footer-contact"><Icon name="pin" size={16}/><span>{settings.address}</span></div><a className="footer-contact" href={`tel:${settings.phone.replace(/\s/g,'')}`}><Icon name="phone" size={15}/>{settings.phone}</a><span className="footer-contact">Business hours: please call to confirm</span>{settings.email&&<span className="footer-contact">{settings.email}</span>}</div></div><div className="footer-bottom"><span>© 2026 KUSUM VET CARE. All Rights Reserved.</span><span>{settings.footer}</span><Link to="/admin/login">Admin Login <Icon name="arrow" size={11} className="inline"/></Link></div></div></footer>}
function SearchModal({close}:{close:()=>void}){const{products}=useStore();const[q,setQ]=useState('');const results=filterProducts(products,{query:q});return <div className="modal-backdrop" onClick={close}><section className="modal search-modal" role="dialog" aria-modal="true" aria-label="Search products" onClick={e=>e.stopPropagation()}><Button variant="ghost" className="icon-btn modal-close" aria-label="Close search" onClick={close}><Icon name="close"/></Button><h2>Find care for your animals</h2><div className="search-input"><Icon name="search"/><input aria-label="Search catalog" autoFocus placeholder="Search products, categories, or animal care…" value={q} onChange={e=>setQ(e.target.value)}/></div><p className="demo-note">{results.length} products found</p><div className="search-results">{results.slice(0,6).map(p=><Link key={p.id} to="/product/$id" params={{id:p.id}} className="search-result" onClick={close}><img src={p.image} alt={p.name}/><div><h3>{p.name}</h3><p>{p.category}</p></div><span className="price">{money(p.sale)}</span></Link>)}{results.length===0&&<p>No products match “{q}”. Try cattle, mineral, or hygiene.</p>}</div><Link className="btn btn-primary mt-5" to="/shop" search={{q}} onClick={close}>View all results <Icon name="arrow" size={16}/></Link></section></div>}
export function PageHeading({title,description}:{title:string;description?:string}){return <div className="page-heading"><div className="container"><div className="breadcrumbs"><Link to="/">Home</Link><Icon name="chevron" size={11}/><span>{title}</span></div><h1>{title}</h1>{description&&<p>{description}</p>}</div></div>}
